{
  "services": {
    "redis": {
      "image": "redis",
    },
    "web": {
      "build": ".",
      "command": "bash -c 'python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000'",
      "volumes": [
        ".:/code",
      ],
      "ports": [
        "127.0.0.1:8000:8000",
        #        "192.168.0.17:8000:8000",
      ],
      "environment": [
        "PYTHONDONTWRITEBYTECODE=true",
        "WEB_CONCURRENCY=1",
        "WEB_RELOAD=true",
        "DJANGO_SECRET_KEY=insecure_key_for_dev",
        "DJANGO_DEBUG=true",
        "DJANGO_ALLOWED_HOSTS=.localhost,127.0.0.1,[::1],192.168.0.21,192.168.1.138,192.168.0.17",
        "DJANGO_DATABASE=sqlite",
        # for console emails
        "DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend",
        # for real emails
        # "DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_FROM_EMAIL}",
        # "DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}",
        # "DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_USER}",
        # "DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_PASSWORD}",

        "DJANGO_ACCOUNT_DEFAULT_HTTP_PROTOCOL=http",
        "DJANGO_CSRF_COOKIE_SECURE=false",
        "DJANGO_SESSION_COOKIE_SECURE=false",
        "DJANGO_SECURE_HSTS_SECONDS=0",
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=false",
        "DJANGO_SECURE_HSTS_PRELOAD=false",
        "DJANGO_SECURE_SSL_REDIRECT=false",
        "DJANGO_ADMINS=root:root@localhost",
        "DJANGO_MANAGERS=root:root@localhost",
        "DJANGO_STAGING_ENVIRONMENT_NAME=dev",
        "DJANGO_CONTACT_PHONE=643 015 716",
        "DJANGO_CONTACT_EMAIL=contacte@femlliga.org",
        "DJANGO_CONTACT_SOCIAL=femlliga",
        "DJANGO_CONTACT_LINKS=https://links.transversalcoop.org/@femlliga/",
        "DJANGO_REDIS_HOST=redis",
      ]
    }
  }
}
