# Generated by Django 4.0.3 on 2022-04-06 08:23

import django.db.models.deletion
from django.db import migrations, models

import femlliga.models


class Migration(migrations.Migration):
    dependencies = [
        ("femlliga", "0002_organization_address_alter_organizationscope_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="needimage",
            name="image",
            field=models.ImageField(
                upload_to=femlliga.models.need_images_directory_path,
                validators=[femlliga.models.LimitFileSize(10)],
            ),
        ),
        migrations.AlterField(
            model_name="offerimage",
            name="image",
            field=models.ImageField(
                upload_to=femlliga.models.offer_images_directory_path,
                validators=[femlliga.models.LimitFileSize(10)],
            ),
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Correu electrònic"),
                            ("WEBSITE", "Lloc web"),
                            ("WHATSAPP", "Whatsapp"),
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("TWITTER", "Twitter"),
                            ("LINKEDIN", "Linkedin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="femlliga.organization",
                    ),
                ),
            ],
        ),
    ]
