# Generated by Django 4.0.3 on 2022-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0004_customuser_last_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('OTHER', 'Altres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='need',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('OTHER', 'Altres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('OTHER', 'Altres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resourceoption',
            name='name',
            field=models.CharField(choices=[('DAILY_USAGE', 'Ús diari'), ('PUNCTUAL_USAGE', 'Ús puntual'), ('PUNCTUAL_MEETINGS', 'Puntualment per a reunions'), ('PUNCTUAL_EVENTS', 'Puntualment per a actes'), ('TRAINING_DIGITAL', 'Digitalització'), ('TRAINING_BUREAUCRACY', "Relacions amb l'administració"), ('TRAINING_EQUALITY', 'Igualtat'), ('TRAINING_ENERGY_SAVING', 'Estalvi energètic'), ('TRAINING_HISTORICAL_MEMORY', 'Memòria històrica'), ('COMMUNITY_MANAGER', 'Gestió de la comunicació (web, xarxes socials, etc.)'), ('INSURANCE', 'Assegurança'), ('AGENCY', 'Gestoria'), ('PROJECT_WRITING', 'Redacció de projectes'), ('DIGITAL_BUREAUCRACY', "Relacions digitals amb l'administració"), ('SOUND_SYSTEM_ACOUSTIC', 'Equip de so per a xerrades'), ('SOUND_SYSTEM_CONCERT', 'Equip de so per a concerts'), ('PROJECTOR', 'Projector'), ('VEHICLE', 'Vehicle'), ('STAGE', 'Escenari'), ('CHAIRS_TABLES', 'Cadires i taules'), ('DISHES', 'Plats, gots i coberts'), ('KITCHEN_EQUIPMENT', 'Material de cuina'), ('CAMPING_EQUIPMENT', "Material d'acampada")], max_length=100, primary_key=True, serialize=False),
        ),
    ]
