# Generated by Django 4.2.5 on 2023-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0007_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accept_communications_automatically',
            field=models.BooleanField(default=True),
        ),
    ]
