# Generated by Django 5.0 on 2023-12-20 10:49

import uuid

from django.db import migrations, models


def set_unique_ids(apps, schema_editor):
    Page = apps.get_model("femlliga", "Page")
    for p in Page.objects.all():
        p.uuid = uuid.uuid4()
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("femlliga", "0008_customuser_accept_communications_automatically"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("ca", "Català"), ("es", "Castellano")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="language",
            field=models.CharField(
                choices=[("ca", "Català"), ("es", "Castellano")],
                default="ca",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("ASSOCIATION", "Associació"),
                    ("COOPERATIVE", "Cooperativa"),
                    ("NONPROFIT_COOPERATIVE", "Cooperativa sense ànim de lucre"),
                    ("FOUNDATION", "Fundació"),
                    ("LABOR_SOCIETY", "Societat laboral"),
                    ("MUTUALITY", "Mutualitat"),
                    ("INSERTION_COMPANY", "Empresa d’inserció"),
                    ("SPECIAL_WORK_CENTER", "Centre especial de treball"),
                    ("PUBLIC_PRIVATE_BASED", "Entitat pública de base privada"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("name", "language")},
        ),
        migrations.RunPython(set_unique_ids, reverse_code=migrations.RunPython.noop),
    ]
