# Generated by Django 5.0 on 2023-12-20 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0009_customuser_language_page_id_page_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.SlugField(),
        ),
    ]
