# Generated by Django 5.0 on 2024-01-09 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0009_customuser_language_page_id_page_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Idioma configurat al navegador'), ('ca', 'Català'), ('es', 'Castellano')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
