# Generated by Django 5.0.2 on 2024-05-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0012_offer_place_accessible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Petició', 'verbose_name_plural': 'Peticions'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacte'},
        ),
        migrations.AlterModelOptions(
            name='contactdenylist',
            options={'verbose_name': 'Contacte bloquejat', 'verbose_name_plural': 'Contactes bloquejats'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organització', 'verbose_name_plural': 'Organitzacions'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Pàgina', 'verbose_name_plural': 'Pàgines'},
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_successful',
            field=models.BooleanField(null=True, verbose_name="S'ha arribat a un acord"),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='communication_accepted',
            field=models.BooleanField(null=True, verbose_name='Conversa per correu'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='communication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Correu enviat el'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Petició enviada el'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='message',
            field=models.TextField(verbose_name='Missatge'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='options',
            field=models.ManyToManyField(to='femlliga.resourceoption', verbose_name='Opcions'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('ALLIANCES', 'Aliances'), ('OTHER', 'Altres')], max_length=100, verbose_name='Recurs'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='resource_type',
            field=models.CharField(choices=[('need', 'Necessitat'), ('offer', 'Oferiment')], max_length=10, verbose_name='Tipus de lliga'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='solicitee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_agreements', to='femlliga.organization', verbose_name='A qui li sol·liciten'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='solicitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_agreements', to='femlliga.organization', verbose_name='Qui sol·licita'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='successful_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acord registrat el'),
        ),
        migrations.AlterField(
            model_name='need',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('ALLIANCES', 'Aliances'), ('OTHER', 'Altres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='resource',
            field=models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Equipaments'), ('ALLIANCES', 'Aliances'), ('OTHER', 'Altres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resourceoption',
            name='name',
            field=models.CharField(choices=[('DAILY_USAGE', 'Ús diari'), ('PUNCTUAL_USAGE', 'Ús puntual'), ('PUNCTUAL_MEETINGS', 'Puntualment per a reunions'), ('PUNCTUAL_EVENTS', 'Puntualment per a actes'), ('TRAINING_DIGITAL', 'Digitalització'), ('TRAINING_BUREAUCRACY', "Relacions amb l'administració"), ('TRAINING_EQUALITY', 'Igualtat'), ('TRAINING_ENERGY_SAVING', 'Estalvi energètic'), ('TRAINING_HISTORICAL_MEMORY', 'Memòria històrica'), ('COMMUNITY_MANAGER', 'Gestió de la comunicació (web, xarxes socials, etc.)'), ('INSURANCE', 'Assegurança'), ('AGENCY', 'Gestoria'), ('PROJECT_WRITING', 'Redacció de projectes'), ('DIGITAL_BUREAUCRACY', "Relacions digitals amb l'administració"), ('SOUND_SYSTEM_ACOUSTIC', 'Equip de so per a xerrades'), ('SOUND_SYSTEM_CONCERT', 'Equip de so per a concerts'), ('PROJECTOR', 'Projector'), ('VEHICLE', 'Vehicle'), ('STAGE', 'Escenari'), ('CHAIRS_TABLES', 'Cadires i taules'), ('DISHES', 'Plats, gots i coberts'), ('KITCHEN_EQUIPMENT', 'Material de cuina'), ('CAMPING_EQUIPMENT', "Material d'acampada"), ('PROJECT_COLLABORATION', 'Col·laboració en projectes'), ('VOLUNTEERING', 'Voluntariat')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
