# Generated by Django 5.0.2 on 2024-05-14 10:03

from django.db import migrations, models


def set_agreement_successful(apps, schema_editor):
    Agreement = apps.get_model("femlliga", "Agreement")
    for a in Agreement.objects.all():
        if a.communication_accepted is False:
            a.agreement_successful = False
            a.successful_date = a.communication_date
        if a.communication_accepted is None:
            a.communication_accepted = True
            a.communication_date = a.date
        a.save()


class Migration(migrations.Migration):
    dependencies = [
        ("femlliga", "0014_emailsent_alter_need_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="origin",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Origen desconegut"),
                    ("MATCHES", "Pàgina «Has lligat?»"),
                    ("SEARCH", "Pàgina «Descobreix»"),
                ],
                default="UNKNOWN",
                max_length=10,
                verbose_name="Origen de la petició",
            ),
        ),
        migrations.RunPython(
            set_agreement_successful, reverse_code=migrations.RunPython.noop
        ),
    ]
