# Generated by Django 5.0.6 on 2024-06-06 14:58

import django.db.models.deletion
from django.db import migrations, models


def migrate_options(apps, schema_editor):
    Need = apps.get_model("femlliga", "Need")
    Offer = apps.get_model("femlliga", "Offer")
    NeedOptionThrough = apps.get_model("femlliga", "NeedOptionThrough")
    OfferOptionThrough = apps.get_model("femlliga", "OfferOptionThrough")
    for n in Need.objects.all():
        for o in n.options.all():
            NeedOptionThrough.objects.create(need=n, option=o)
    for n in Offer.objects.all():
        for o in n.options.all():
            OfferOptionThrough.objects.create(offer=n, option=o)


class Migration(migrations.Migration):
    dependencies = [
        ("femlliga", "0016_message_read_alter_agreement_agreement_successful_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceoption",
            name="name",
            field=models.CharField(
                choices=[
                    ("DAILY_USAGE", "Ús diari"),
                    ("PUNCTUAL_USAGE", "Ús puntual"),
                    ("PUNCTUAL_MEETINGS", "Puntualment per a reunions"),
                    ("PUNCTUAL_EVENTS", "Puntualment per a actes"),
                    ("TRAINING_DIGITAL", "Digitalització"),
                    ("TRAINING_BUREAUCRACY", "Relacions amb l'administració"),
                    ("TRAINING_EQUALITY", "Igualtat i Feminismes"),
                    ("TRAINING_ENERGY_SAVING", "Eficiència i estalvi energètic"),
                    ("TRAINING_HISTORICAL_MEMORY", "Memòria històrica"),
                    ("TRAINING_ARTS", "Arts i cultura"),
                    ("TRAINING_PROJECTS", "Redacció de projectes"),
                    ("COMMUNITY_MANAGER", "Comunicació"),
                    ("INSURANCE", "Assegurances"),
                    ("AGENCY", "Gestoria"),
                    ("PROJECT_WRITING", "Redacció de projectes"),
                    ("DIGITAL_BUREAUCRACY", "Relacions digitals amb l'administració"),
                    ("SERVICE_PARTICIPATION", "Participació"),
                    ("SERVICE_REPAIR", "Reparació, manteniment i reutilització"),
                    (
                        "EQUIPMENT_EVENTS",
                        "Material d'esdeveniments, fires i exposicions",
                    ),
                    ("VEHICLE", "Vehicle"),
                    ("CHAIRS_TABLES", "Mobiliari"),
                    ("KITCHEN_EQUIPMENT", "Material de cuina"),
                    ("CAMPING_EQUIPMENT", "Material d'acampada"),
                    ("EQUIPMENT_DIY", "Material de bricolatge"),
                    ("EQUIPMENT_SPORTS", "Material esportiu"),
                    ("EQUIPMENT_EDUCATION", "Material pedagògic i de sensibilització"),
                    ("PROJECT_COLLABORATION", "Col·laboració en projectes"),
                    ("VOLUNTEERING", "Voluntariat"),
                    ("PUBLICITY", "Difusió"),
                ],
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="NeedOptionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="femlliga.need"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="femlliga.resourceoption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="need",
            name="need_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="needs",
                through="femlliga.NeedOptionThrough",
                to="femlliga.resourceoption",
            ),
        ),
        migrations.CreateModel(
            name="OfferOptionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="femlliga.offer"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="femlliga.resourceoption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="offers",
                through="femlliga.OfferOptionThrough",
                to="femlliga.resourceoption",
            ),
        ),
        migrations.RunPython(migrate_options, reverse_code=migrations.RunPython.noop),
    ]
