# Generated by Django 5.0.6 on 2024-07-15 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0016_message_read_alter_agreement_agreement_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_immediate_announcement_communications_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resourceoption',
            name='name',
            field=models.CharField(choices=[('DAILY_USAGE', 'Ús diari'), ('PUNCTUAL_USAGE', 'Ús puntual'), ('PUNCTUAL_MEETINGS', 'Puntualment per a reunions'), ('PUNCTUAL_EVENTS', 'Puntualment per a actes'), ('TRAINING_DIGITAL', 'Digitalització'), ('TRAINING_BUREAUCRACY', "Relacions amb l'administració"), ('TRAINING_EQUALITY', 'Igualtat i Feminismes'), ('TRAINING_ENERGY_SAVING', 'Eficiència i estalvi energètic'), ('TRAINING_HISTORICAL_MEMORY', 'Memòria històrica'), ('TRAINING_ARTS', 'Arts i cultura'), ('TRAINING_PROJECTS', 'Redacció de projectes'), ('COMMUNITY_MANAGER', 'Comunicació'), ('INSURANCE', 'Assegurances'), ('AGENCY', 'Gestoria'), ('PROJECT_WRITING', 'Redacció de projectes'), ('DIGITAL_BUREAUCRACY', "Relacions digitals amb l'administració"), ('SERVICE_PARTICIPATION', 'Participació'), ('SERVICE_REPAIR', 'Reparació, manteniment i reutilització'), ('EQUIPMENT_EVENTS', "Material d'esdeveniments, fires i exposicions"), ('VEHICLE', 'Vehicle'), ('CHAIRS_TABLES', 'Mobiliari'), ('KITCHEN_EQUIPMENT', 'Material de cuina'), ('CAMPING_EQUIPMENT', "Material d'acampada"), ('EQUIPMENT_DIY', 'Material de bricolatge'), ('EQUIPMENT_SPORTS', 'Material esportiu'), ('EQUIPMENT_EDUCATION', 'Material pedagògic i de sensibilització'), ('PROJECT_COLLABORATION', 'Col·laboració en projectes'), ('VOLUNTEERING', 'Voluntariat'), ('PUBLICITY', 'Difusió')], max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.TextField(verbose_name='Títol')),
                ('description', models.TextField(verbose_name='Descripció')),
                ('resource', models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Materials'), ('ALLIANCES', 'Aliances'), ('OTHER', 'Altres')], max_length=100, verbose_name='Recurs')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femlliga.resourceoption', verbose_name='Opció')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='femlliga.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_on', models.DateTimeField(auto_now_add=True, verbose_name='Contacte enviat el')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField(verbose_name='Nom')),
                ('message', models.TextField(verbose_name='Missatge')),
                ('read', models.BooleanField(default=False)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='femlliga.announcement')),
            ],
            options={
                'ordering': ['-received_on'],
            },
        ),
    ]
