# Generated by Django 5.0.6 on 2024-06-17 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0017_alter_resourceoption_name_needoptionthrough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_immediate_external_communications_received',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_on', models.DateTimeField(auto_now_add=True, verbose_name='Contacte enviat el')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField(verbose_name='Nom')),
                ('message', models.TextField(verbose_name='Missatge')),
                ('resource', models.CharField(choices=[('PLACE', 'Local'), ('TRAINING', 'Formació'), ('SERVICE', 'Servei'), ('EQUIPMENT', 'Materials'), ('ALLIANCES', 'Aliances'), ('OTHER', 'Altres')], max_length=100, verbose_name='Recurs')),
                ('read', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='femlliga.resourceoption', verbose_name='Opció')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_external_contacts', to='femlliga.organization', verbose_name='Organització contactada')),
            ],
            options={
                'ordering': ['-received_on'],
            },
        ),
    ]
