# Generated by Django 5.0.6 on 2024-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0017_customuser_notify_immediate_announcement_communications_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='welcome_email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
