# Generated by Django 5.1 on 2024-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0020_alter_resourceoption_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('requests_count', models.IntegerField(default=0)),
            ],
        ),
    ]
