# Generated by Django 5.1.4 on 2025-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femlliga', '0021_reportstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWordDenyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Paraula bloquejada',
                'verbose_name_plural': 'Paraules bloquejades',
            },
        ),
    ]
