# Generated by Django 5.0.7 on 2024-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
